name: Random Commit 1

on:
  schedule:
    - cron: '*/5 1 * * *'
  workflow_dispatch:
  
jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Make changes
        run: 
          echo "Random Commit made at $(date '+%Y-%m-%d %H:%M:%S')" > log.txt

      - name: Commit and push if changed
        run: |
          git pull
          git config --global user.email "wanzaty.id@gmail.com"
          git config --global user.name "wanzaty"
          git add -A
          git commit -m "Daily update $(date '+%Y-%m-%d %H:%M:%S')"
          git push
